const languages = {"en-AU":"English","zh-CN":"简体中文","zh-HK":"繁體中文","yue-HK":"廣東話","ja-JP":"日本語","es-ES":"Español"};
const ui = {
  "en-AU": {nowAt:"NOW AT",systemNarration:"System narration",systemNarrationHint:"AI personal channel",systemDefinition:"AI-generated personal narration for your selected language.",listenGuide:"Listen to guide",listenGuideHint:"Guide live channel",guideLiveDefinition:"The human guide’s live multilingual channel.",providerChecking:"Checking translation service…",providerReady:"OpenAI realtime translation ready",providerDisconnected:"Not connected · test mode",liveUnavailableTitle:"Guide broadcast is not connected",liveUnavailableBody:"The translation provider can be tested with this device’s microphone. This is not the guide’s live audio.",testTranslation:"Test on this device",connecting:"Connecting…",stopTranslation:"Stop test",ask:"Ask guide",askHint:"Send a question",rate:"Rate guide",rateHint:"Share feedback",play:"Play narration",askTitle:"Ask Alex",askBody:"Write in your language. The guide sees the original question and language.",questionPlaceholder:"What would you like to know?",send:"Send to guide",rateTitle:"How was Alex?",rateBody:"Your feedback appears in the private tour review.",commentPlaceholder:"Anything you especially enjoyed?",submitRating:"Submit rating"},
  "zh-CN": {nowAt:"当前位置",systemNarration:"系统讲解",systemNarrationHint:"AI 个人讲解频道",systemDefinition:"AI 根据你选择的语言生成的个人讲解。",listenGuide:"听导游",listenGuideHint:"真人导游实时频道",guideLiveDefinition:"真人导游的实时多语种频道。",providerChecking:"正在检查翻译服务…",providerReady:"OpenAI 实时翻译已就绪",providerDisconnected:"未连接 · 测试模式",liveUnavailableTitle:"导游广播尚未连接",liveUnavailableBody:"翻译服务可用本机麦克风测试；这不是导游的实时音频。",testTranslation:"在本机测试",connecting:"正在连接…",stopTranslation:"停止测试",ask:"问导游",askHint:"发送问题",rate:"评价导游",rateHint:"分享感受",play:"播放讲解",askTitle:"问 Alex",askBody:"请用你的语言提问，导游会看到原文和语种。",questionPlaceholder:"你想了解什么？",send:"发送给导游",rateTitle:"Alex 的讲解怎么样？",rateBody:"你的反馈只会进入导游的行程复盘。",commentPlaceholder:"有什么特别喜欢的吗？",submitRating:"提交评价"},
  "zh-HK": {nowAt:"目前位置",systemNarration:"系統講解",systemNarrationHint:"AI 個人講解頻道",systemDefinition:"AI 按照你選擇的語言生成個人講解。",listenGuide:"聽導遊",listenGuideHint:"真人導遊實時頻道",guideLiveDefinition:"真人導遊的實時多語種頻道。",providerDisconnected:"未連接 · 測試模式",liveUnavailableTitle:"實時翻譯尚未連接",liveUnavailableBody:"本地原型尚未連接語音識別、翻譯和語音合成服務。目前不會翻譯或播放任何導遊實時音訊。",waitingProvider:"等待服務連接",ask:"問導遊",askHint:"傳送問題",rate:"評價導遊",rateHint:"分享感受",play:"播放講解",askTitle:"問 Alex",askBody:"請用你的語言提問，導遊會看到原文和語種。",questionPlaceholder:"你想了解甚麼？",send:"傳送給導遊",rateTitle:"Alex 的講解怎麼樣？",rateBody:"你的意見只會進入導遊的行程復盤。",commentPlaceholder:"有甚麼特別喜歡嗎？",submitRating:"提交評價"},
  "yue-HK": {nowAt:"而家位置",systemNarration:"系統講解",systemNarrationHint:"AI 個人講解頻道",systemDefinition:"AI 按你揀嘅語言生成嘅個人講解。",listenGuide:"聽導遊",listenGuideHint:"真人導遊直播頻道",guideLiveDefinition:"真人導遊嘅實時多語種頻道。",providerDisconnected:"未連接 · 測試模式",liveUnavailableTitle:"實時翻譯未連接",liveUnavailableBody:"本地原型未連接語音識別、翻譯同語音合成服務，而家唔會翻譯或播放導遊直播音訊。",waitingProvider:"等候服務連接",ask:"問導遊",askHint:"傳送問題",rate:"評價導遊",rateHint:"分享感受",play:"播放講解",askTitle:"問 Alex",askBody:"用你自己嘅語言問，導遊會見到原文同語種。",questionPlaceholder:"你想知啲咩？",send:"傳送俾導遊",rateTitle:"Alex 講得點？",rateBody:"你嘅意見只會放入導遊私人行程復盤。",commentPlaceholder:"有咩你特別鍾意？",submitRating:"提交評價"},
  "ja-JP": {nowAt:"現在地",systemNarration:"システム解説",systemNarrationHint:"AI 個人チャンネル",systemDefinition:"選択した言語でAIが生成する個人向け解説です。",listenGuide:"ガイドを聞く",listenGuideHint:"ガイドのライブ配信",guideLiveDefinition:"人間のガイドによるリアルタイム多言語チャンネルです。",providerDisconnected:"未接続 · テストモード",liveUnavailableTitle:"リアルタイム翻訳は未接続です",liveUnavailableBody:"このローカル試作版では音声認識・翻訳・音声合成サービスが未接続です。ライブ音声の翻訳や再生は行われません。",waitingProvider:"サービス接続待ち",ask:"ガイドに質問",askHint:"質問を送る",rate:"ガイドを評価",rateHint:"感想を共有",play:"解説を再生",askTitle:"Alex に質問",askBody:"あなたの言語で入力してください。ガイドには原文と言語が表示されます。",questionPlaceholder:"何を知りたいですか？",send:"ガイドに送信",rateTitle:"Alex はどうでしたか？",rateBody:"フィードバックは非公開のツアーレビューに反映されます。",commentPlaceholder:"特に良かったことは？",submitRating:"評価を送信"},
  "es-ES": {nowAt:"AHORA EN",systemNarration:"Narración del sistema",systemNarrationHint:"Canal personal de IA",systemDefinition:"Narración personal generada por IA en el idioma que elegiste.",listenGuide:"Escuchar al guía",listenGuideHint:"Canal en vivo del guía",guideLiveDefinition:"Canal multilingüe en vivo del guía humano.",providerDisconnected:"Sin conexión · modo de prueba",liveUnavailableTitle:"La traducción en vivo no está conectada",liveUnavailableBody:"Los servicios de voz a texto, traducción y voz no están conectados en este prototipo local. No se traduce ni reproduce audio en vivo del guía.",waitingProvider:"Esperando conexión del servicio",ask:"Preguntar",askHint:"Enviar una pregunta",rate:"Valorar guía",rateHint:"Compartir opinión",play:"Reproducir narración",askTitle:"Pregunta a Alex",askBody:"Escribe en tu idioma. El guía verá el texto original y el idioma.",questionPlaceholder:"¿Qué te gustaría saber?",send:"Enviar al guía",rateTitle:"¿Qué tal Alex?",rateBody:"Tu opinión aparece en la revisión privada del tour.",commentPlaceholder:"¿Qué te gustó especialmente?",submitRating:"Enviar valoración"}
};
const select = document.getElementById("language-select"); Object.entries(languages).forEach(([value,label]) => select.add(new Option(label,value)));
const detected = navigator.languages?.find((language) => languages[language]) || Object.keys(languages).find((key) => key.split("-")[0] === navigator.language.split("-")[0]) || "en-AU";
let locale = localStorage.getItem("tour-locale") || detected; select.value = locale;
const joinToken = new URLSearchParams(location.search).get("join");
let visitorId = sessionStorage.getItem(`visitor:${SESSION_ID}`); let selectedRating = 0; let activeQuestionId = sessionStorage.getItem("active-question"); let stopLiveTranslation = null;
const translatedTags = {"en-AU":["Engaging","Knowledgeable","Great answers","Well organised","Caring"],"zh-CN":["讲解有趣","知识丰富","回答问题好","行程安排好","服务贴心"],"zh-HK":["講解有趣","知識豐富","回答問題好","行程安排好","服務貼心"],"yue-HK":["講得有趣","知識豐富","解答得好","行程安排好","服務貼心"],"ja-JP":["楽しい解説","知識が豊富","回答が良い","進行が良い","親切"],"es-ES":["Ameno","Mucho conocimiento","Buenas respuestas","Bien organizado","Atento"]};
function copy(key) { return ui[locale]?.[key] ?? ui["en-AU"][key]; }
function applyLanguage() { document.documentElement.lang = locale; document.querySelectorAll("[data-i18n]").forEach((el) => el.textContent = copy(el.dataset.i18n)); document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => el.placeholder = copy(el.dataset.i18nPlaceholder)); renderTags(); loadNarration(); refreshTranslationStatus(); }
async function join() {
  if (localStorage.getItem("tour-guide-profile")) throw new Error(locale === "zh-CN" ? "此设备已作为导游端使用，请让游客在自己的手机上扫码。" : "This device is in guide mode. Ask visitors to scan on their own phones.");
  if (!joinToken) throw new Error(locale === "zh-CN" ? "请扫描导游手机上的二维码加入行程。" : "Scan the QR code on the guide's phone to join.");
  if (!visitorId) { const result = await api(`/api/sessions/${SESSION_ID}/join`, {method:"POST",body:JSON.stringify({locale,join_token:joinToken})}); visitorId=result.visitor_id; sessionStorage.setItem(`visitor:${SESSION_ID}`,visitorId); }
}
async function loadNarration() { const narration = await api(`/api/sessions/${SESSION_ID}/narration`); document.getElementById("narration-text").textContent = narration.outputs[locale] || narration.outputs["en-AU"]; }
async function refresh() { const session = await api(`/api/sessions/${SESSION_ID}`); document.getElementById("visitor-route").textContent=session.route_name.split("·")[0].trim(); document.getElementById("visitor-place").innerHTML=escapeHtml(session.current_place).replace(" ","<br />"); document.getElementById("visitor-topic").textContent=session.current_topic; if(activeQuestionId){const q=session.questions.find(item=>item.id===activeQuestionId);if(q){const status=document.getElementById("answer-status");status.classList.remove("hidden");status.innerHTML=q.answer?`<strong>Guide replied</strong><p>${escapeHtml(q.answer)}</p>`:"✓ Sent to the guide · waiting for a reply";}} }
select.addEventListener("change",()=>{locale=select.value;localStorage.setItem("tour-locale",locale);speechSynthesis.cancel();applyLanguage();});
document.querySelectorAll("[data-action]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-action]").forEach(b=>b.classList.toggle("active",b===button));document.querySelectorAll(".visitor-panel").forEach(p=>p.classList.toggle("hidden",p.id!==`${button.dataset.action}-view`));}));
document.getElementById("play-narration").addEventListener("click",()=>{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(document.getElementById("narration-text").textContent);utterance.lang=locale;utterance.rate=.92;speechSynthesis.speak(utterance);toast("Playing on your current audio output");});
document.getElementById("speech-note").textContent="Audio uses your phone’s current speaker or Bluetooth route.";
async function refreshTranslationStatus() {
  try {
    const status = await api("/api/translation/status");
    document.querySelector("#translation-provider-status span").textContent = status.configured ? copy("providerReady") : copy("providerDisconnected");
    document.getElementById("test-live-translation").disabled = !status.configured;
  } catch (_) { document.querySelector("#translation-provider-status span").textContent = copy("providerDisconnected"); }
}
document.getElementById("test-live-translation").addEventListener("click", async () => {
  const button = document.getElementById("test-live-translation");
  if (stopLiveTranslation) { stopLiveTranslation(); stopLiveTranslation = null; button.textContent = copy("testTranslation"); return; }
  button.textContent = copy("connecting"); document.getElementById("live-transcript").textContent = "";
  try {
    stopLiveTranslation = await LiveTranslation.connect({targetLocale:locale, visitorId, audioElement:document.getElementById("translated-audio"), onTranscript:(delta)=>document.getElementById("live-transcript").textContent += delta, onState:(state)=>{if(state==="connected")button.textContent=copy("stopTranslation");}});
  } catch (error) { button.textContent = copy("testTranslation"); toast(error.message); }
});
document.getElementById("send-question").addEventListener("click",async()=>{const text=document.getElementById("question-text").value.trim();if(!text)return toast("Please write a question first");const q=await api(`/api/sessions/${SESSION_ID}/questions`,{method:"POST",body:JSON.stringify({visitor_id:visitorId,text,locale})});activeQuestionId=q.id;sessionStorage.setItem("active-question",q.id);toast("Question sent to Alex");refresh();});
function renderStars(){document.getElementById("stars").innerHTML=[1,2,3,4,5].map(n=>`<button aria-label="${n} stars" class="${n<=selectedRating?'selected':''}" data-star="${n}">★</button>`).join("");document.querySelectorAll("[data-star]").forEach(b=>b.addEventListener("click",()=>{selectedRating=Number(b.dataset.star);renderStars();}));}
function renderTags(){document.getElementById("rating-tags").innerHTML=translatedTags[locale].map(t=>`<button data-tag="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("");document.querySelectorAll("[data-tag]").forEach(b=>b.addEventListener("click",()=>b.classList.toggle("selected")));}
document.getElementById("send-rating").addEventListener("click",async()=>{if(!selectedRating)return toast("Choose a star rating first");const tags=[...document.querySelectorAll("[data-tag].selected")].map(b=>b.dataset.tag);await api(`/api/sessions/${SESSION_ID}/ratings`,{method:"POST",body:JSON.stringify({visitor_id:visitorId,score:selectedRating,tags,comment:document.getElementById("rating-comment").value})});toast("Thank you — rating added to Tour Review");});
renderStars();applyLanguage();applySessionBrand().catch(() => {});join().then(refresh).catch(error => { document.querySelector(".visitor-main").innerHTML = `<section class="access-gate"><img data-brand-logo src="/assets/alonora-logo-card.jpg" alt="ALONORA" /><h1>${escapeHtml(error.message)}</h1><p>${locale === "zh-CN" ? "游客入口只通过导游端二维码开放。" : "The visitor experience is available only through the guide's QR code."}</p></section>`; applySessionBrand().catch(() => {}); });setInterval(() => { if (visitorId) refresh(); },2500);
