const languages = {"en-AU":"English","zh-CN":"简体中文","zh-HK":"繁體中文","yue-HK":"廣東話","ja-JP":"日本語","es-ES":"Español"};
const ui = {
  "en-AU": {nowAt:"NOW AT",listen:"Listen",listenHint:"Current story",ask:"Ask guide",askHint:"Send a question",rate:"Rate guide",rateHint:"Share feedback",play:"Play narration",askTitle:"Ask Alex",askBody:"Write in your language. The guide sees the original question and language.",questionPlaceholder:"What would you like to know?",send:"Send to guide",rateTitle:"How was Alex?",rateBody:"Your feedback appears in the private tour review.",commentPlaceholder:"Anything you especially enjoyed?",submitRating:"Submit rating"},
  "zh-CN": {nowAt:"当前位置",listen:"听讲解",listenHint:"当前故事",ask:"问导游",askHint:"发送问题",rate:"评价导游",rateHint:"分享感受",play:"播放讲解",askTitle:"问 Alex",askBody:"请用你的语言提问，导游会看到原文和语种。",questionPlaceholder:"你想了解什么？",send:"发送给导游",rateTitle:"Alex 的讲解怎么样？",rateBody:"你的反馈只会进入导游的行程复盘。",commentPlaceholder:"有什么特别喜欢的吗？",submitRating:"提交评价"},
  "zh-HK": {nowAt:"目前位置",listen:"聽講解",listenHint:"目前故事",ask:"問導遊",askHint:"傳送問題",rate:"評價導遊",rateHint:"分享感受",play:"播放講解",askTitle:"問 Alex",askBody:"請用你的語言提問，導遊會看到原文和語種。",questionPlaceholder:"你想了解甚麼？",send:"傳送給導遊",rateTitle:"Alex 的講解怎麼樣？",rateBody:"你的意見只會進入導遊的行程復盤。",commentPlaceholder:"有甚麼特別喜歡嗎？",submitRating:"提交評價"},
  "yue-HK": {nowAt:"而家位置",listen:"聽講解",listenHint:"而家故事",ask:"問導遊",askHint:"傳送問題",rate:"評價導遊",rateHint:"分享感受",play:"播放講解",askTitle:"問 Alex",askBody:"用你自己嘅語言問，導遊會見到原文同語種。",questionPlaceholder:"你想知啲咩？",send:"傳送俾導遊",rateTitle:"Alex 講得點？",rateBody:"你嘅意見只會放入導遊私人行程復盤。",commentPlaceholder:"有咩你特別鍾意？",submitRating:"提交評價"},
  "ja-JP": {nowAt:"現在地",listen:"解説を聞く",listenHint:"現在のストーリー",ask:"ガイドに質問",askHint:"質問を送る",rate:"ガイドを評価",rateHint:"感想を共有",play:"解説を再生",askTitle:"Alex に質問",askBody:"あなたの言語で入力してください。ガイドには原文と言語が表示されます。",questionPlaceholder:"何を知りたいですか？",send:"ガイドに送信",rateTitle:"Alex はどうでしたか？",rateBody:"フィードバックは非公開のツアーレビューに反映されます。",commentPlaceholder:"特に良かったことは？",submitRating:"評価を送信"},
  "es-ES": {nowAt:"AHORA EN",listen:"Escuchar",listenHint:"Historia actual",ask:"Preguntar",askHint:"Enviar una pregunta",rate:"Valorar guía",rateHint:"Compartir opinión",play:"Reproducir narración",askTitle:"Pregunta a Alex",askBody:"Escribe en tu idioma. El guía verá el texto original y el idioma.",questionPlaceholder:"¿Qué te gustaría saber?",send:"Enviar al guía",rateTitle:"¿Qué tal Alex?",rateBody:"Tu opinión aparece en la revisión privada del tour.",commentPlaceholder:"¿Qué te gustó especialmente?",submitRating:"Enviar valoración"}
};
const select = document.getElementById("language-select"); Object.entries(languages).forEach(([value,label]) => select.add(new Option(label,value)));
const detected = navigator.languages?.find((language) => languages[language]) || Object.keys(languages).find((key) => key.split("-")[0] === navigator.language.split("-")[0]) || "en-AU";
let locale = localStorage.getItem("tour-locale") || detected; select.value = locale;
let visitorId = sessionStorage.getItem(`visitor:${SESSION_ID}`); let selectedRating = 0; let activeQuestionId = sessionStorage.getItem("active-question");
const translatedTags = {"en-AU":["Engaging","Knowledgeable","Great answers","Well organised","Caring"],"zh-CN":["讲解有趣","知识丰富","回答问题好","行程安排好","服务贴心"],"zh-HK":["講解有趣","知識豐富","回答問題好","行程安排好","服務貼心"],"yue-HK":["講得有趣","知識豐富","解答得好","行程安排好","服務貼心"],"ja-JP":["楽しい解説","知識が豊富","回答が良い","進行が良い","親切"],"es-ES":["Ameno","Mucho conocimiento","Buenas respuestas","Bien organizado","Atento"]};
function applyLanguage() { document.documentElement.lang = locale; document.querySelectorAll("[data-i18n]").forEach((el) => el.textContent = (ui[locale] || ui["en-AU"])[el.dataset.i18n]); document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => el.placeholder = (ui[locale] || ui["en-AU"])[el.dataset.i18nPlaceholder]); renderTags(); loadNarration(); }
async function join() { if (!visitorId) { const result = await api(`/api/sessions/${SESSION_ID}/join`, {method:"POST",body:JSON.stringify({locale})}); visitorId=result.visitor_id; sessionStorage.setItem(`visitor:${SESSION_ID}`,visitorId); } }
async function loadNarration() { const narration = await api(`/api/sessions/${SESSION_ID}/narration`); document.getElementById("narration-text").textContent = narration.outputs[locale] || narration.outputs["en-AU"]; }
async function refresh() { const session = await api(`/api/sessions/${SESSION_ID}`); document.getElementById("visitor-route").textContent=session.route_name.split("·")[0].trim(); document.getElementById("visitor-place").innerHTML=escapeHtml(session.current_place).replace(" ","<br />"); document.getElementById("visitor-topic").textContent=session.current_topic; if(activeQuestionId){const q=session.questions.find(item=>item.id===activeQuestionId);if(q){const status=document.getElementById("answer-status");status.classList.remove("hidden");status.innerHTML=q.answer?`<strong>Guide replied</strong><p>${escapeHtml(q.answer)}</p>`:"✓ Sent to the guide · waiting for a reply";}} }
select.addEventListener("change",()=>{locale=select.value;localStorage.setItem("tour-locale",locale);speechSynthesis.cancel();applyLanguage();});
document.querySelectorAll("[data-action]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-action]").forEach(b=>b.classList.toggle("active",b===button));document.querySelectorAll(".visitor-panel").forEach(p=>p.classList.toggle("hidden",p.id!==`${button.dataset.action}-view`));}));
document.getElementById("play-narration").addEventListener("click",()=>{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(document.getElementById("narration-text").textContent);utterance.lang=locale;utterance.rate=.92;speechSynthesis.speak(utterance);toast("Playing on your current audio output");});
document.getElementById("speech-note").textContent="Audio uses your phone’s current speaker or Bluetooth route.";
document.getElementById("send-question").addEventListener("click",async()=>{const text=document.getElementById("question-text").value.trim();if(!text)return toast("Please write a question first");const q=await api(`/api/sessions/${SESSION_ID}/questions`,{method:"POST",body:JSON.stringify({visitor_id:visitorId,text,locale})});activeQuestionId=q.id;sessionStorage.setItem("active-question",q.id);toast("Question sent to Alex");refresh();});
function renderStars(){document.getElementById("stars").innerHTML=[1,2,3,4,5].map(n=>`<button aria-label="${n} stars" class="${n<=selectedRating?'selected':''}" data-star="${n}">★</button>`).join("");document.querySelectorAll("[data-star]").forEach(b=>b.addEventListener("click",()=>{selectedRating=Number(b.dataset.star);renderStars();}));}
function renderTags(){document.getElementById("rating-tags").innerHTML=translatedTags[locale].map(t=>`<button data-tag="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join("");document.querySelectorAll("[data-tag]").forEach(b=>b.addEventListener("click",()=>b.classList.toggle("selected")));}
document.getElementById("send-rating").addEventListener("click",async()=>{if(!selectedRating)return toast("Choose a star rating first");const tags=[...document.querySelectorAll("[data-tag].selected")].map(b=>b.dataset.tag);await api(`/api/sessions/${SESSION_ID}/ratings`,{method:"POST",body:JSON.stringify({visitor_id:visitorId,score:selectedRating,tags,comment:document.getElementById("rating-comment").value})});toast("Thank you — rating added to Tour Review");});
renderStars();applyLanguage();join().then(refresh);setInterval(refresh,2500);
